### ISSUE TITLE
Create backend for android UI

### ISSUE THREAD

**Issue by R0H1T-RAJU** [Allen-ISD-Computer-Science/REPO_CybSecAttackVectors_2024#33]

**Comment by Lavanyasatish1** [comment]
- The backend code is functional with the UI, but there are a couple of bugs causing locations not to appear consistently. 
- Previous problems such as locations not showing up at all have been resolved as improvements have been made to the initial code. 
-  I'm encountering difficulty committing the updated backend code, thus it isn't reflected in the repository.
